### ISSUE TITLE
What are the sink configuration settings for this?

### ISSUE THREAD

**Issue by boberty88** [gilt/flume-logstash-sink#2]
Hi, looking to use the flume-logstash-sink to experiment with different collectors for my data environment but there is no documentation on how to configure the sink? I would like to know how to specify the ES cluster host and port number.

**Comment by javierarrieta** [comment]
Hi, nothing changes apart from the two configuration attributes mentioned in the README

This is extracted from the flume docs with the serializer and index builder cusomised for an agent named `a1` and a sink `k1`:

```
a1.sinks.k1.type = org.apache.flume.sink.elasticsearch.ElasticSearchSink
a1.sinks.k1.hostNames = 127.0.0.1:9200,127.0.0.2:9300
a1.sinks.k1.indexName = foo_index
a1.sinks.k1.indexType = bar_type
a1.sinks.k1.clusterName = foobar_cluster
a1.sinks.k1.batchSize = 500
a1.sinks.k1.ttl = 5
a1.sinks.k1.serializer = com.gilt.flume.elasticsearch.ElasticSearchLogStashEventSerializerV12
a1.sinks.k1.indexNameBuilder = com.gilt.flume.elasticsearch.TimeBasedIndexNameBuilderV12
```
